# Use the official PostgreSQL image as a base image
FROM postgres:latest

# Set environment variables for the database
ENV POSTGRES_DB=taxi_database
ENV POSTGRES_USER=inristaka
ENV POSTGRES_PASSWORD=mypassword

# Expose the PostgreSQL port
EXPOSE 5432
